### ISSUE TITLE
does not consume resources.

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/CauldronWitchery#15]
Hello, during an invocation the resources are not all consumed

For example, an elder guardian Need 40x Salmon , 40x shard and 40 Crystals + 10level. the plugin will consume 1 stack of the 3 items and not the other 2 items, If he consumes the Salmon, he will remain the shard and the crystal. Levels are never consumed.

**Comment by charlyg31** [comment]
Update: it consumes the item drop first.

**Comment by BONNe** [comment]
Can you share output of `bentobox version`

**Comment by charlyg31** [comment]
![Uploading Capture.PNG…]()
Paper 1.19.2

**Comment by charlyg31** [comment]
![Capture](https://user-images.githubusercontent.com/22028655/185754295-0f005cc3-7e41-4957-b046-51287a15f9e6.PNG)
Paper 1.19.2

**Comment by BONNe** [comment]
While I am figuring out what is the issue, you can change that:
- recipes require exact item count
- all dropped items in cauldrons are removed 

Options are available in CauldronWitchery config.

**Comment by charlyg31** [comment]
Requiert exact item is "false"
All drop item remove is "true"

**Comment by charlyg31** [comment]
I changed to exact item, now it takes all the items but still not the experience.
