### ISSUE TITLE
Preventing spam of lightnings

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/CauldronWitchery#4]
#### Is your feature request related to a problem?

People are spamming by clicking on cauldron and summoning lightnings, which are beeing heard on the whole world :/ It would be awesome to set cooldown to summoning or just removing ("brokening") cauldron or giving damage, when summoning is not properly completed. Or the best oprion - all of it

**Comment by BONNe** [comment]
Partially implemented.
Currently, there is no ability to set cooldown.

**Comment by BONNe** [comment]
Lightning is removed in version 2.0.

The reason for removal was that players were able to abuse this feature to create charged creepers and light the nether portals without flint and steel.

Also, after rewriting the logic and mechanic of the addon, it will work better without lightning and just with particle effects that are coming from the cauldron.
