### ISSUE TITLE
Books contain only "Invalid book data"

### ISSUE THREAD

**Issue by mindw0rm** [BentoBoxWorld/CauldronWitchery#6]
### Description

When creating a book, its content consists only of the word "*invalid book tag*" 
Tried with both English and the German locale, as well as really short texts, since I assumed it might be a length problem. 

#### Steps to reproduce the behavior:

Set up a magic cauldron filled with water.
Take a stick (or bone, haven't tested anythign else) in the main hand and a book in the off hand.
Right click  the cauldron. You get the illegible book. 

#### Server / BentoBox information:

```
08.02 03:05:45 [Server] Server thread/INFO Es läuft SPIGOT 1.15.2.
08.02 03:05:45 [Server] Server thread/INFO BentoBox-Version: 1.11.0
08.02 03:05:45 [Server] Server thread/INFO Datenbank: SQLITE
08.02 03:05:45 [Server] Server thread/INFO Geladene Spielewelten:
08.02 03:05:45 [Server] Server thread/INFO acidisland_world (AcidIsland): Oberwelt, [nether_color]Nether, [end_color]Ende
08.02 03:05:45 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Oberwelt, [nether_color]Nether, [end_color]Ende
08.02 03:05:45 [Server] Server thread/INFO caveblock-world (CaveBlock): Oberwelt, [nether_color]Nether, [end_color]Ende
08.02 03:05:45 [Server] Server thread/INFO Geladene Addons:
08.02 03:05:45 [Server] Server thread/INFO AcidIsland 1.11.0 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO BentoBox-InvSwitcher 1.6.0 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Biomes 1.6.0.1-SNAPSHOT-b151 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO BSkyBlock 1.11.0 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO CauldronWitchery 1.5.0.0-SNAPSHOT-#12 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO CaveBlock 1.11.0 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Challenges 0.9.0-SNAPSHOT-b398 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO DimensionalTrees 1.6.0-SNAPSHOT-b80 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Greenhouses 1.0.1-SNAPSHOT-b120 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Level 1.9.3 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Likes 1.7.0-SNAPSHOT-b17 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b95 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO TwerkingForTrees 1.1.2 (ENABLED)
08.02 03:05:45 [Server] Server thread/INFO Warps 1.9.3-SNAPSHOT-b222 (ENABLED)
```

#### Screenshots / Server log

Nothing helpful (error messages etc.) in the server log :(

#### Expected behavior / Additional context

The book should contain the texts specified in the locale file. 
It _did_ work when I first tried, which should have been 10/2019. That was with an older MC version, I think it was 1.14.4, but maybe even 1.13.2 ...

**Comment by mindw0rm** [comment]
I did some testing and found out that the problem occurs if the book title is longer than 32 characters. 
So the solution seems to be to simply use shorter titles (I'll go with "5 GV I - Animals" to "5 GV IV - End" for now). 

Maybe make two different strings for title and displayName? displayName can be longer, but should contain line breaks, or else most of it will be put off-screen. 

@BONNe it says that I assigned you to this issue, but I can't remember doing that. Must have been an accidental click, sorry :/

**Comment by vandon1** [comment]
This still appears to be an issue with build #21 on the BentoBoxWorld Jenkins. No errors in the log, everything looks like it works but the book does not contain anything except the invalid tag

**Comment by BONNe** [comment]
It is the length of book title/author.

**Comment by vandon1** [comment]
> 
> 
> It is the length of book title/author.

How do I change this? Am I able to change it?

**Comment by BONNe** [comment]
Yes in the locale.
I will work on addon next month when I will fix the issues in release.

**Comment by vandon1** [comment]
Found it! Thanks. It's not in the config directory like you'd think. It is up a level in the BentoBox/locales directory. This confused me a little

**Comment by BONNe** [comment]
Books are reworked in 2.0 version and now they should not be with invalid tags anymore.
