### ISSUE TITLE
Support 1.17

### ISSUE THREAD

**Issue by aurel85** [BentoBoxWorld/CauldronWitchery#9]
Hi,

The latest version of the plugin does not work in 1.17.1 (I have the latest version of BentoBox and PaperSpigot).

![Capture](https://user-images.githubusercontent.com/24486147/126050219-13ab0689-5b7a-4a24-9360-750b23eaa94f.PNG)

Nothing happens in the game, no message, the block just lands on the cauldron filled with water.
No error in the console.

Thank you in advance.

**Comment by BONNe** [comment]
I made changes that enable this addon 1.17 version. 

You can download it from: https://ci.codemc.io/job/BentoBoxWorld/job/CauldronWitchery/

**Comment by aurel85** [comment]
Everything is ok, thank you !
